# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perfect.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 583)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRun = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRun.sizePolicy().hasHeightForWidth())
        self.btnRun.setSizePolicy(sizePolicy)
        self.btnRun.setMinimumSize(QtCore.QSize(62, 31))
        self.btnRun.setMaximumSize(QtCore.QSize(62, 31))
        self.btnRun.setText("Run")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("play_48px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRun.setIcon(icon)
        self.btnRun.setIconSize(QtCore.QSize(50, 45))
        self.btnRun.setAutoDefault(False)
        self.btnRun.setDefault(False)
        self.btnRun.setFlat(True)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout.addWidget(self.btnRun)
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setMinimumSize(QtCore.QSize(52, 31))
        self.btnClear.setMaximumSize(QtCore.QSize(62, 31))
        self.btnClear.setText("Clear")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("broom_48px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClear.setIcon(icon1)
        self.btnClear.setIconSize(QtCore.QSize(40, 45))
        self.btnClear.setFlat(True)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.left = QtWidgets.QToolBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left.sizePolicy().hasHeightForWidth())
        self.left.setSizePolicy(sizePolicy)
        self.left.setMinimumSize(QtCore.QSize(230, 0))
        self.left.setFrameShape(QtWidgets.QFrame.Box)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setLineWidth(1)
        self.left.setObjectName("left")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 270, 363))
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.function = QtWidgets.QListWidget(self.page)
        self.function.setObjectName("function")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.function.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.function.addItem(item)
        self.verticalLayout.addWidget(self.function)
        self.left.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 270, 363))
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.subscript = QtWidgets.QPushButton(self.page_2)
        self.subscript.setObjectName("subscript")
        self.gridLayout_3.addWidget(self.subscript, 0, 0, 1, 1)
        self.superscript = QtWidgets.QPushButton(self.page_2)
        self.superscript.setObjectName("superscript")
        self.gridLayout_3.addWidget(self.superscript, 0, 1, 1, 1)
        self.left.addItem(self.page_2, "")
        self.middle = QtWidgets.QSplitter(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middle.sizePolicy().hasHeightForWidth())
        self.middle.setSizePolicy(sizePolicy)
        self.middle.setOrientation(QtCore.Qt.Vertical)
        self.middle.setChildrenCollapsible(False)
        self.middle.setObjectName("middle")
        self.textBoard = QtWidgets.QTextEdit(self.middle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBoard.sizePolicy().hasHeightForWidth())
        self.textBoard.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.textBoard.setFont(font)
        self.textBoard.setFrameShape(QtWidgets.QFrame.Box)
        self.textBoard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBoard.setObjectName("textBoard")
        self.tabWidget = QtWidgets.QTabWidget(self.middle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textInspector = QtWidgets.QTextEdit(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setItalic(True)
        self.textInspector.setFont(font)
        self.textInspector.setReadOnly(True)
        self.textInspector.setObjectName("textInspector")
        self.verticalLayout_3.addWidget(self.textInspector)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textMessage = QtWidgets.QTextEdit(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Century751 BT")
        font.setPointSize(11)
        font.setItalic(True)
        self.textMessage.setFont(font)
        self.textMessage.setReadOnly(True)
        self.textMessage.setObjectName("textMessage")
        self.verticalLayout_4.addWidget(self.textMessage)
        self.tabWidget.addTab(self.tab_6, "")
        self.right = QtWidgets.QFrame(self.splitter)
        self.right.setMinimumSize(QtCore.QSize(268, 0))
        self.right.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.right.setFrameShape(QtWidgets.QFrame.Box)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.left.setCurrentIndex(1)
        self.left.layout().setSpacing(3)
        self.tabWidget.setCurrentIndex(1)
        self.function.currentTextChanged['QString'].connect(self.textBoard.insertPlainText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matcox"))
        __sortingEnabled = self.function.isSortingEnabled()
        self.function.setSortingEnabled(False)
        item = self.function.item(0)
        item.setText(_translate("MainWindow", "Base"))
        item = self.function.item(1)
        item.setText(_translate("MainWindow", "Solve"))
        self.function.setSortingEnabled(__sortingEnabled)
        self.left.setItemText(self.left.indexOf(self.page), _translate("MainWindow", "Functions"))
        self.subscript.setText(_translate("MainWindow", "Subscript"))
        self.superscript.setText(_translate("MainWindow", "Superscript"))
        self.left.setItemText(self.left.indexOf(self.page_2), _translate("MainWindow", "Symbols"))
        self.textBoard.setPlaceholderText(_translate("MainWindow", "Writing Board"))
        self.textInspector.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans MS\'; font-size:10pt; font-weight:400; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Inspector"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Message"))
